# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190320_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=20),
            preserve_default=False,
        ),
    ]
