# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_entry_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.CharField(default='cash', max_length=20),
            preserve_default=False,
        ),
    ]
