# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20190323_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='lastname',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
